version: "3.8"
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: myusername
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydbname
    ports:
      - "5432:5432"
  graphql-engine:
    image: hasura/graphql-engine:v2.0.10
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://myusername:mypassword@postgres:5432/mydbname
      HASURA_GRAPHQL_ADMIN_SECRET: Q2dkJ401j1PmbjPcqedy4uwc2hgwzTMaUZ4zgWJqbUfvwcnzWaswS4rISFy50T68
      HASURA_GRAPHQL_JWT_SECRET: >
        {
          "type": "RS256",
          "jwk_url": "https://dev-q8uqn5yntv2fh046.us.auth0.com/.well-known/jwks.json",
          "claims_namespace_path": "$['https://hasura.io/jwt/claims']",
          "claims_format": "json"
        }
